### ISSUE TITLE
Question: async computation in the agent

### ISSUE THREAD

**Issue by filiph** [gaaclarke/agents#7]
Hi!

I'm trying to use `isolate_agents` but it's unclear to me how to deal with asynchronous computation in the isolate.

For example, how would you rewrite [this function](https://github.com/gaaclarke/romeo_juliet/blob/main/lib/main.dart#L66-L78) in the Romeo & Juliet example if you couldn't use `*Sync` variants of file functions?

```dart
  agent.update((state) {
    File file = File('${state.documentsDir!.path}/$index.rot');
    if (file.existsSync()) {
      String encoded = file.readAsStringSync();
      return _DecoderState(state.documentsDir, _rot13Decode(encoded));
    } else {
      return _DecoderState(state.documentsDir, null);
    }
  });
```

Or, for a simplified example, how can I do something like the following?

```dart
agent.update((result) async => result += await Future.delayed(Duration(seconds: 1), () => 42));
```

**Comment by gaaclarke** [comment]
You can't =)  Sending async functions to agents would break the contract that all tasks are executed serially.

We could potentially implement that but It would be a bit tricky since the agent would have to start caching the async functions instead of letting the event loop store them.  It is a bit misleading too since we essentially have to make an async function synchronous in order for it to work.

You can reopen and rewrite this issue or make a new one that is a feature request.  Please include the specifics of the use case you are running into.
